In [115]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [116]:
df = pd.read_csv(r"E:\Data Science by SRK\Machine_learning\project\Medical Insurance Costs Dataset\cleaned_dataset_medical_cost_insurance.csv")

In [117]:
df

      age  gender     bmi  children  smoker      charges
0      19       0  27.900         0       1  16884.92400
1      18       1  33.770         1       0   1725.55230
2      28       1  33.000         3       0   4449.46200
3      33       1  22.705         0       0  21984.47061
4      32       1  28.880         0       0   3866.85520
...   ...     ...     ...       ...     ...          ...
1332   50       1  30.970         3       0  10600.54830
1333   18       0  31.920         0       0   2205.98080
1334   18       0  36.850         0       0   1629.83350
1335   21       0  25.800         0       0   2007.94500
1336   61       0  29.070         0       1  29141.36030

[1337 rows x 6 columns]

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   gender    1337 non-null   int64
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   int64
 5   charges   1337 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 62.8 KB

**X and y**

In [119]:
X = df.drop('charges', axis=1)
y = df['charges']

# Train Test Split

In [120]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 9)

# Modelling AND Evaluation

**Applying Hyperparameter tuning for Ridge regression**

In [121]:
from sklearn.model_selection import GridSearchCV

# model
from sklearn.linear_model import Ridge
estimator = Ridge()
estimator

Ridge()

In [122]:
# parameters and value
param_grid = {"alpha" : list(range(1,100))}


# Identifying best parameter value(alpha) within the given values for the given data
model_hp = GridSearchCV(estimator, param_grid, cv=5, scoring = 'r2')
model_hp

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                                   25, 26, 27, 28, 29, 30, ...]},
             scoring='r2')

In [123]:
model_hp.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                   14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                                   25, 26, 27, 28, 29, 30, ...]},
             scoring='r2')

In [124]:
model_hp.best_params_

{'alpha': 1}

In [125]:
# All in one cell

from sklearn.model_selection import GridSearchCV

# model
from sklearn.linear_model import Ridge
estimator = Ridge()

# parameters and value
param_grid = {"alpha" : list(range(1,100))}


# Identifying best parameter value(alpha) within the given values for the given data
model_hp = GridSearchCV(estimator, param_grid, cv=5, scoring = 'r2')

model_hp.fit(X_train, y_train)
model_hp.best_params_

{'alpha': 1}

**Modelling Ridge Regression using best hyperparameters**

In [126]:
X = X.drop("gender", axis = 1)
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 9)



from sklearn.linear_model import Ridge
ridge_best = Ridge(alpha=1)
ridge_best.fit(X_train,y_train)

print("Intercept : ", ridge_best.intercept_)
print("coefficients : ", ridge_best.coef_)
print("=============================================")

# Prediction and evaluation on train_data
ypred_train = ridge_best.predict(X_train)

from sklearn.metrics import r2_score
print("Train_R2 : ", r2_score(y_train, ypred_train))

from sklearn.model_selection import cross_val_score
print("Cross_val_score : ", cross_val_score(ridge_best, X_train, y_train, cv = 5).mean())

# Prediction & E valuation on test data
ypred_test = ridge_best.predict(X_test)
print("R2_score : ", r2_score(y_test, ypred_test))

Intercept :  -12169.96052617402
coefficients :  [  264.52523944   318.02306062   411.94009856 23844.02920948]
=============================================
Train_R2 :  0.7593159963279539
Cross_val_score :  0.7538892261526557
R2_score :  0.700853795012164

# Prediction on new data

In [127]:
input_data = {
    "age" : 31,
    "gender" : "female",
    "bmi" : 25.74,
    "children" : 0,
    "smoker" : "no",
    "region" : "northeast"
}

In [128]:
df_test = pd.DataFrame(input_data, index=[0])
df_test

   age  gender    bmi  children smoker     region
0   31  female  25.74         0     no  northeast

In [129]:
df_test.drop(['region', 'gender'], axis = 1,inplace = True)
df_test["smoker"].replace({"no" : 0, "yes" : 1}, inplace = True)
df_test

C:\Users\SHRI\AppData\Local\Temp\ipykernel_13788\164796112.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test["smoker"].replace({"no" : 0, "yes" : 1}, inplace = True)
C:\Users\SHRI\AppData\Local\Temp\ipykernel_13788\164796112.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test["smoker"].replace({"no" : 0, "yes" : 1}, inplace = True)

   age    bmi  children  smoker
0   31  25.74         0       0

In [130]:
ridge_best.predict(df_test)

array([4216.23547689])

In [131]:
 (240.49582387*31)  + (342.34989485*25.74) +  (459.23321156*0 )+( 17839.98676013*0) -10909.149143382454

5358.307690026546